name = "StableLinearAlgebra"
uuid = "7d06c537-f8ff-4c22-91e1-ce4088e3cfd7"
authors = ["Benjamin Cohen-Stead <benwcs@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
